/* 
  DO NOT EDIT THIS FILE

  Please do not modify files in the test directory.
  This can cause the tests to give incorrect results or fail, making it harder to identify and fix issues in the code.
  Make any necessary changes to the original file and re-run the tests to ensure they are still working correctly.
*/
import { Reporter, TestContext } from "@jest/reporters";
import { AggregatedResult } from "@jest/test-result";

type CustomReporter = Pick<Reporter, "onRunComplete">;

export default class TestReporter implements CustomReporter {
  constructor() {}

  onRunComplete(_: Set<TestContext>, results: AggregatedResult) {
    console.log("\ntotal test cases:", results.numTotalTests);
    console.log("\npassed test cases:", results.numPassedTests);
    console.log("\nfailed test cases:", results.numFailedTests);
  }
}
